default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: lucas
  password: Lts9406338
  host: localhost

development:
  <<: *default
  database: ECommerce2_development

test:
  <<: *default
  database: ECommerce2_test

production:
  <<: *default
  database: ECommerce2_production
  username: lucas
  password: <%= ENV['DATABASE_PASSWORD'] %>